# Generated by Django 3.1.5 on 2021-01-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
